feat: Assets\Scripts\BattleProcessor.cs(79,50): error CS0246: The type or namespace name 'BaseController' could not be found (are you missing a using directive or an assembly reference?) というエラーが出たから修正してほしい。BaseController.csってやつがないのかな？ (by UnityCraft AI)